In [47]:
import torch
from torch import optim, nn
from test_data import *

In [43]:
[name for name in dir(optim) if not name.startswith("_")]

['ASGD',
 'Adadelta',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'NAdam',
 'Optimizer',
 'RAdam',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 'lr_scheduler',
 'swa_utils']

In [46]:
params = torch.tensor([1.0, 0], requires_grad=True)
lr = 1e-5
optimizer = optim.SGD([params], lr=lr)

In [48]:
tp = model(tu, *params)
loss = lossfn(tp, tc)
loss

tensor(1763.8848, grad_fn=<MeanBackward0>)

In [49]:
loss.backward()

In [73]:
optimizer.step()
params

tensor([-0.0842, -0.0198], requires_grad=True)

In [74]:
params = torch.tensor([1.0, 0], requires_grad=True)
lr = 1e-2
optimizer = optim.SGD([params], lr=lr)

In [75]:
tp = model(tun, *params)
loss = lossfn(tp, tc)

In [ ]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [77]:
optimizer.zero_grad()
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [78]:
loss.backward()
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [80]:
optimizer.step()
print(optimizer)
print(params)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
tensor([1.7761, 0.1064], requires_grad=True)


In [82]:
def train(n, optimizer, params, tu, tc):
    for e in range(1, n + 1):
        tp = model(tu, *params)
        loss = lossfn(tp, tc)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if e < 6 or e % 500 == 0:
            print(f"Epoch {e}, Loss {loss.item():.6f}")

    return params


params = torch.tensor([1.0, 0], requires_grad=True)
lr = 1e-2
optimizer = optim.SGD([params], lr=lr)
tun = tu * 0.1
train(n=5000, optimizer=optimizer, params=params, tu=tun, tc=tc)

Epoch 1, Loss 80.364342
Epoch 2, Loss 37.574913
Epoch 3, Loss 30.871077
Epoch 4, Loss 29.756193
Epoch 5, Loss 29.507153
Epoch 500, Loss 7.860120
Epoch 1000, Loss 3.828538
Epoch 1500, Loss 3.092191
Epoch 2000, Loss 2.957698
Epoch 2500, Loss 2.933134
Epoch 3000, Loss 2.928648
Epoch 3500, Loss 2.927830
Epoch 4000, Loss 2.927679
Epoch 4500, Loss 2.927652
Epoch 5000, Loss 2.927647


tensor([  5.3671, -17.3012], requires_grad=True)

In [83]:
params = torch.tensor([1.0, 0], requires_grad=True)
lr = 1e-1
optimizer = optim.Adam([params], lr=lr)

In [84]:
train(n=2000, optimizer=optimizer, params=params, tu=tu, tc=tc)

Epoch 1, Loss 1763.884766
Epoch 2, Loss 1334.349121
Epoch 3, Loss 967.816040
Epoch 4, Loss 664.756348
Epoch 5, Loss 424.630066
Epoch 500, Loss 7.612900
Epoch 1000, Loss 3.086698
Epoch 1500, Loss 2.928578
Epoch 2000, Loss 2.927646


tensor([  0.5367, -17.3021], requires_grad=True)